### ISSUE TITLE
Option for not showing button, even with only a single type

### ISSUE THREAD

**Issue by readeral** [sanity-io/dashboard-widget-document-list#6]
Sometimes you might like to show a list of items which isn't necessarily created in the studio. My example is a list of users registered to the website which is actually updated from auth0 via the js library.

I've made a pull request #5 which adds an option for setting createButton to false

**Comment by corygibbons** [comment]
Came looking to see if this was an option, I would this 👍

**Comment by etuned** [comment]
I am currently developing a website for a client where this design pattern is needed. Would love to help implement it.

**Comment by rexxars** [comment]
Thanks to @readeral this is now implemented - `showCreateButton: false` :) 
Sorry for the very late follow-up!
